### ISSUE TITLE
TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by TheEssemCraft** [lolPants/retrotext#2]
I'm trying to use this module with my Discord bot, but it keeps throwing this error:

```
TypeError: Cannot set property '0' of undefined
    at RetroText.setLine1 (/home/pi/esmBot/node_modules/retrotext/src/index.js:57:18)
    at RetroText.setLine (/home/pi/esmBot/node_modules/retrotext/src/index.js:98:21)
    at Object.exports.run (/home/pi/esmBot/commands/retro.js:28:36)
    at module.exports (/home/pi/esmBot/events/message.js:52:7)
    at Client.emit (events.js:182:13)
    at MessageCreateAction.handle (/home/pi/esmBot/node_modules/discord.js/src/client/actions/MessageCreate.js:24:14)
    at MessageCreateHandler.handle (/home/pi/esmBot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:5:53)
    at WebSocketPacketManager.handle (/home/pi/esmBot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:99:65)
    at WebSocketConnection.onPacket (/home/pi/esmBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:322:35)
    at WebSocketConnection.onMessage (/home/pi/esmBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:285:10)
```

**Comment by lolPants** [comment]
Fixed in `3.0.1`
